### PR TITLE
Add an About dialog

### PR DESCRIPTION
**Pull request by brarcher**

### CODE REVIEW

**Comment by brarcher** [comment]
@paulle This pull request add an About dialog, which requires several strings to be translated. Would you be available to provide German translations for the strings below?

```
    <string name="about">About</string>
    <string name="app_copyright_fmt">Copyright 2016-<xliff:g>%s</xliff:g> Branden Archer</string>
    <string name="app_license">Licensed under the GPLv3.</string>
    <string name="about_title_fmt">About <xliff:g id="app_name">%s</xliff:g></string>
    <string name="debug_version_fmt">Version: <xliff:g id="version">%s</xliff:g></string>
    <string name="app_revision_fmt">Revision Information: <xliff:g id="app_revision_url">%s</xliff:g></string>
    <string name="app_libraries"><xliff:g id="app_name">%s</xliff:g> uses the following third-party libraries: <xliff:g id="app_libraries_list">%s</xliff:g></string>
    <string name="ok">OK</string>
```

Thanks!

**Comment by paulle** [comment]
here you go:

string name="about">Über</string>
     <string name="app_copyright_fmt">Copyright 
2016-<xliff:g>%s</xliff:g> Branden Archer</string>
     <string name="app_license">Lizensiert unter der GPLv3.</string>
     <string name="about_title_fmt">Über <xliff:g 
id="app_name">%s</xliff:g></string>
     <string name="debug_version_fmt">Version: <xliff:g 
id="version">%s</xliff:g></string>
     <string name="app_revision_fmt">Revision Information: <xliff:g 
id="app_revision_url">%s</xliff:g></string>
     <string name="app_libraries"><xliff:g id="app_name">%s</xliff:g> 
benutzt die folgenden third-party libraries: <xliff:g 
id="app_libraries_list">%s</xliff:g></string>
     <string name="ok">OK</string>


Am 15.05.2016 um 05:10 schrieb Branden Archer:
> |<string name="about">About</string> <string 
> name="app_copyright_fmt">Copyright 2016-<xliff:g>%s</xliff:g> Branden 
> Archer</string> <string name="app_license">Licensed under the 
> GPLv3.</string> <string name="about_title_fmt">About <xliff:g 
> id="app_name">%s</xliff:g></string> <string 
> name="debug_version_fmt">Version: <xliff:g 
> id="version">%s</xliff:g></string> <string 
> name="app_revision_fmt">Revision Information: <xliff:g 
> id="app_revision_url">%s</xliff:g></string> <string 
> name="app_libraries"><xliff:g id="app_name">%s</xliff:g> uses the 
> following third-party libraries: <xliff:g 
> id="app_libraries_list">%s</xliff:g></string> <string 
> name="ok">OK</string> |

**Comment by brarcher** [comment]
Thanks, @paulle!

Android lint says the following about the app_license string:

> "Lizensiert" is a common misspelling. Did you mean "Lizenziert"?

Should I make this change?

**Comment by brarcher** [comment]
I've made the spelling change to "Lizenziert". If it is incorrect, let me know.

**Comment by paulle** [comment]
Yes you are right. My fault.

Am 15. Mai 2016 16:02:04 MESZ, schrieb Branden Archer <notifications@github.com>:
>Thanks, @paulle!
>
>Android lint says the following about the app_license string:
>
>> "Lizensiert" is a common misspelling. Did you mean "Lizenziert"?
>
>Should I make this change?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/brarcher/budget-watch/pull/38#issuecomment-219287553

-- 

mit K-9 Mail gesendet.

**Comment by paulle** [comment]
It's correct.

Am 15. Mai 2016 16:20:42 MESZ, schrieb Branden Archer <notifications@github.com>:
>I've made the spelling change to "Lizenziert". If it is incorrect, let
>me know.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/brarcher/budget-watch/pull/38#issuecomment-219288547

-- 

mit K-9 Mail gesendet.

**Pull request merged**
