### PR TITLE
Create FAQ.md

### PR DESCRIPTION
**Pull request by olayhemy**
A Frequently Asked Question section (FAQs) is without a doubt the most commonly used tool in self-service. Service users tend to feel that their question is the most important question, and they are right. With Frequently Asked Questions, service users will find answers to possible questions. Kindly merge this!

### CODE REVIEW

**Comment by olayhemy** [comment]
Sorry for replying late! 

I'm still interested in it, kindly reply when you get my comment

**Comment by olayhemy** [comment]
Where should the file be added?

**Comment by brarcher** [comment]
There is a wiki on github for the project here: [link](https://github.com/brarcher/budget-watch/wiki). Should that be the spot for the FAQ? From there, I think people can update it without a pull request.

**Comment by olayhemy** [comment]
Awesome!

Since no need to make a pull request, how can I add the file to the wiki? This is because I don't know how to do that.

**Comment by brarcher** [comment]
I've only ever edited wiki pages. There is a New Page button I see on the top right of the wiki. Do you see this? I would start there, and look up online about the wiki format and how it works. Then I can learn from your example. (:

**Pull request closed without merging**
