### PR TITLE
Put transaction adding error messages into strings.xml

### PR DESCRIPTION
**Pull request by brarcher**

### CODE REVIEW

**Comment by brarcher** [comment]
@paulle I noticed that there were a few error strings that were missing from the strings.xml file. This pull request will add them. Could you translate the following to German so the translation will remain complete? Thanks in advance!
```
<string name="budgetMissing">"No budget selected"</string>
<string name="valueMissing">"Value is empty"</string>
<string name="valueInvalid">"Value invalid"</string>
<string name="dateInvalid">"Date invalid"</string>
```

**Comment by paulle** [comment]
German:

|<string name="budgetMissing">"Kein Budget ausgewählt"</string> <string 
name="valueMissing">"Wert ist leer"</string> <string 
name="valueInvalid">"Wert ist ungültig"</string> <string 
name="dateInvalid">"Datum ist ungültig"</string> Here you have the 
missing strings, don't hesitate to contact me if you have more strings 
to translate. I've no idea of how to code, so I can only help with 
translation. |





Am 21.02.2016 um 07:15 schrieb Branden Archer:
> |<string name="budgetMissing">"No budget selected"</string> <string 
> name="valueMissing">"Value is empty"</string> <string 
> name="valueInvalid">"Value invalid"</string> <string 
> name="dateInvalid">"Date invalid"</string> |

**Comment by paulle** [comment]
German:

|<string name="budgetMissing">"Kein Budget ausgewählt"</string> <string 
name="valueMissing">"Wert fehlt"</string> <string 
name="valueInvalid">"Wert ist ungültig"</string> <string 
name="dateInvalid">"Datum ist ungültig"</string> I corrected line 2. It 
"sounds" a little bit better. Here you have the missing strings, don't 
hesitate to contact me if you have more strings to translate. I've no 
idea of how to code, so I can only help with translation. |





Am 21.02.2016 um 07:15 schrieb Branden Archer:

||



Am 21.02.2016 um 07:15 schrieb Branden Archer:

**Comment by brarcher** [comment]
Thanks @paulle!

**Pull request merged**
