### PR TITLE
Add ability to share a receipt image

### PR DESCRIPTION
**Pull request by brarcher**

### CODE REVIEW

**Comment by brarcher** [comment]
@paulle This change adds the ability to share a receipt image. It adds one string, "Share". I think that this translates to "Aktie". Can you confirm?

**Comment by paulle** [comment]
No, in this case you are wrong. In this context the german verb "teilen" is correct.

Am 16. Mai 2016 15:33:24 MESZ, schrieb Branden Archer <notifications@github.com>:
>@paulle This change adds the ability to share a receipt image. It adds
>one string, "Share". I think that this translates to "Aktie". Can you
>confirm?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/brarcher/budget-watch/pull/39#issuecomment-219425634

-- 

mit K-9 Mail gesendet.

**Comment by brarcher** [comment]
Thanks!

**Comment by paulle** [comment]
Excuse me, found an error in my translation. Look here: 
https://github.com/brarcher/budget-watch/blob/master/app/src/main/res/values-de/strings.xml 
in line 47 and 48.
<string name="expensesTitle">Einnahmen</string> 	<string 
name="revenuesTitle">Ausgaben</string> 	

Things are reverse.
it should be like this:
<string name="expensesTitle">Ausgaben</string> 	<string 
name="revenuesTitle">Einnahmen</string> 	

because expenses is Ausgaben and revenues is Einnahmen. I'm sorry.

Am 16.05.2016 um 15:47 schrieb Branden Archer:

**Comment by brarcher** [comment]
No problem. Pull request https://github.com/brarcher/budget-watch/pull/44 will correct this.

**Pull request merged**
