### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by redfast00**

### CODE REVIEW

**Comment by zatoichi-engineer** [comment]
The pull request failed because Android expects ```'``` to be escaped, namely ```\'```.

A project was setup on Transifex for managing the translations of this project. Can you please contribute translations on the [Transifex page for the project](https://www.transifex.com/na-243/budget-watch) instead? (The README mentioning this as well, in case you are looking for the address later). Using Transifex should help managing future translations as well, as new strings are added.

If you have any difficulty working with Transifex, please let me know. Thanks for your interest in adding translations for the project!

**Comment by brarcher** [comment]
The pull request failed because Android expects ' to be escaped, namely \'.

A project was setup on Transifex for managing the translations of this project. Can you please contribute translations on the Transifex page for the project instead? (The README mentioning this as well, in case you are looking for the address later). Using Transifex should help managing future translations as well, as new strings are added.

If you have any difficulty working with Transifex, please let me know. Thanks for your interest in adding translations for the project!

**Comment by redfast00** [comment]
I escaped the single quote, sorry for that. Tests pass now, is this okay?

**Comment by brarcher** [comment]
Looks good, thanks!

Can you add this translation on Transifex, so that if new strings are added you can be notified, in case you are interested in adding new translations in the future?

**Pull request merged**
