### PR TITLE
Add ability to search transactions

### PR DESCRIPTION
**Pull request by brarcher**
This adds a search icon in the action bar at the top of the transaction view. 

image

When clicked it will allow one to enter in a string to search. The string will look through the description, account, value, and note fields to see if the query string exists in any of those fields. Each match is displayed.

image

image

### CODE REVIEW

**Comment by brarcher** [comment]
@paulle & @bezcitu
This pull request adds the following strings:
```
    <string name="search">Search</string>
    <string name="searchHint">Search&#8230;</string>
    <string name="searchEmptyExpenses">No matching expense transactions.</string>
    <string name="searchEmptyRevenues">No matching revenue transactions.</string>
```
Could these please be translated into German so they can be included in the next release?

Thanks!

**Comment by paulle** [comment]
German

|<string name="search">Suchen</string> <string 
name="searchHint">Suchen&#8230;</string> <string 
name="searchEmptyExpenses">Keine übereinstimmenden 
Ausgabentransaktionen.</string> <string name="searchEmptyRevenues">|||Keine übereinstimmenden Einahmentransaktionen|.</string>|




Am 05.02.2017 um 03:20 schrieb Branden Archer:
> |<string name="search">Search</string> <string 
> name="searchHint">Search&#8230;</string> <string 
> name="searchEmptyExpenses">No matching expense transactions.</string> 
> <string name="searchEmptyRevenues">No matching revenue 
> transactions.</string>|

**Comment by brarcher** [comment]
Thanks!

**Comment by brarcher** [comment]
German translations pulled in from https://github.com/brarcher/budget-watch/pull/72

**Pull request merged**
