### PR TITLE
Capitalize first letter on some fields

### PR DESCRIPTION
**Pull request by brarcher**
https://github.com/brarcher/budget-watch/issues/105

### CODE REVIEW

**Comment by MarioMey** [comment]
Why copitalize every word? I think that is only for personal names.

**Comment by brarcher** [comment]
The fields which start with a capital letter are the Budget, Name of a company, Name of an account, and Note. The first three (in my experience, anyway) are proper nouns and the latter could be a sentence. It seemed reasonable to have those all start with a capital letter. Do you disagree?

**Comment by MarioMey** [comment]
I would capitalize **every word** only Name of a company. Everything else, (I think) it should be only first letter of the sentence, not every word.

Look at this image, from this github!

imagen

Expenses names are capitalized only first letter (e.g: "Dong Yang market" ("Dong Yang" is a personal name inside the expense name)). Also notes (eg: "Grossery deserts").

For Expenses names, I use "Ferretería", "Verdulería", "Supermercado" ("Hardware store", "Grosery", "Market") or "Nafta", "Golosinas" ("Fuel", "Candys"). None of these are personal names and don't have to be capitalized in every word.

**Comment by brarcher** [comment]
I think that you might be right. The note field should have the input type textCapSentences instead of textCapWords. The other fields are fine as is. Do you agree?

**Comment by MarioMey** [comment]
No, but it's not a big deal for me to use as is ;).
If you change only Note type, it would be great too, thanks!

**Pull request merged**
